# Generated by Django 4.2.6 on 2023-10-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer", models.CharField(db_index=True, max_length=255)),
                ("item", models.CharField(db_index=True, max_length=255)),
                ("total", models.DecimalField(decimal_places=2, max_digits=6)),
                ("quantity", models.PositiveIntegerField()),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
